services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - homelab_proxy
    volumes:
      - ./homepage:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.${DOMAIN}
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.home.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=3000"

